spring.application.name=springboot

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Render DB (you can keep this OR move it to env too)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://shinkansen.proxy.rlwy.net:36253/record_system_db}

spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}